### ISSUE TITLE
Inkonsistente for= bzw. id= auf der Erklärungsseite des Markitup-Addons

### ISSUE THREAD

**Issue by interweave-media** [phoebusryan/rex_markitup#16]
Unter "Beispiel: Module Input (Markdown)" ist beim Label for="markitup_textile_1" gesetzt, das sollte sicher for="markitup_markdown_1" heißen. Bei "Beispiel: Module Input (Textile)" ist vergleichbar verkehrt.

**Comment by phoebusryan** [comment]
Das ist natürlich richtig. Der Editor war ursprünglich nur für Textile gedacht; mittlerweile ist er offen für jegliche WYMIWYM-Editoren. Ich habe den Fehler aber korrigiert. Im nächsten Update (1.2.1) wird er raus sein.
