### ISSUE TITLE
Bildeinpflege via Icon gibt unkorrekten Dateipfad in der Ausgabe

### ISSUE THREAD

**Issue by interweave-media** [phoebusryan/rex_markitup#17]
Das Einpflegen eines Bildes via Icon des Markitup/textile-Eingabefeldes gibt nicht den korrekten Dateipfad aus. Siehe Screens ->

![markitup-01](https://cloud.githubusercontent.com/assets/16902827/12588240/fca6c91c-c457-11e5-874c-b5e1f919f40b.png)
![markitup-02](https://cloud.githubusercontent.com/assets/16902827/12588243/002c6da8-c458-11e5-941d-ce301cd3a3fa.png)

Früher (redaxo 4.x und älter) wurde auch zuerst ein Bildfilter gewählt, bevor die Datei ausgesucht werden konnte.

**Comment by phoebusryan** [comment]
Danke für das Issue, ich schau es mir gleich an. Was aber meinst du mit "Bildfilter"?

**Comment by phoebusryan** [comment]
So, das Problem ist auch gelöst. Vor den Bildnamen wird nun folgendes gesetzt:

"index.php?rex_media_type=markitupImage&rex_media_file="

..damit man die Bilder via mediamanager bearbeiten kann.

**Comment by polarpixel** [comment]
Mit Bildfilter meint er die Image Manager Presets, also z.B. markitupImage.
Hier eine Auswahl zwischenzuschalten ist aber vermutlich nicht ganz einfach.

**Comment by phoebusryan** [comment]
Sehe dafür keinen wirklichen Usecase. Jetzt gebe ich wie oben geschrieben einen vordefinierten mit. Wenn dieser individuell sein soll, kann ich da auch den Profilnamen anhängen oder ähnliches. Aber eben, ein Usecase wäre durchaus sinnvoll bevor ich sowas einbaue.

**Comment by tbaddade** [comment]
> Vor den Bildnamen wird nun folgendes gesetzt:
> "index.php?rex_media_type=markitupImage&rex_media_file="
> ..damit man die Bilder via mediamanager bearbeiten kann.

Das empfinde ich als schlechteste Variante überhaupt. Stelle dir zwei drei Bilder in einem längeren Fließtext vor. Oder zwei unterschiedliche Textareas die unterschiedliche Mediatypen benötigen. Ist nicht ganz einfach das Thema, daher würde ich auf `/media/`gehen (prüfen ob Redaxo in einem Unterordner installiert ist.). Eventuell wäre auch eine Methode bei der Modulausgabe sinnvoll, um ggf. die Bilderpfade anzupassen (Regex). Einfach einem media_type übergeben oder eine externe Methode die mir einen passenden Pfad ausgibt.

**Comment by interweave-media** [comment]
@polarpixel: "Hier eine Auswahl zwischenzuschalten ist aber vermutlich nicht ganz einfach."
Mag sein, nur in der bisherigen Ausführung, also Markitup-Addon unter redaxo 4.x war das ja so. Man konnte dort nach Klick auf das Image-Icon zuerst den Mediatype wählen (wenn welche eingestellt waren natürlich).

**Comment by phoebusryan** [comment]
Machbar wäre es schon. Schwierig wäre es auch wirklich. Ich sehe nur den Sinn nicht. Bilder gehören einfach aus meiner Sicht nicht in einen Editor. Also generell nicht. Vorallem nicht wenn der Kunde den Editor bedienen muss/soll und da dann jeweils noch ein Mediatyp auswählen soll...

**Comment by interweave-media** [comment]
ok - vielleicht sollte man dann aber auch konsequenterweise als default das image aus den Profiles (textile_full und markdown_full) einfach herausnehmen. Sonst stiftet es eher Verwirrung, wenn es dann nicht richig funktioniert.

**Comment by phoebusryan** [comment]
inwiefern? So funktioniert es ja nun. Wenn es den Mediatyp nicht gibt, wird das Bild normal eingebunden. Man kann es aber optional bearbeiten/resizen/croppen wenn man möchte.

**Comment by interweave-media** [comment]
Das war darauf bezogen, dass du - durchaus berechtigtt - sagtest, dass Bilder generell nicht per Editor eingepflegt werden sollten. Dann finde ich eben, dass man konsequenter Weise das auch gar nicht erst anbietet (per Icon). Denke aber, dass das Thema hier abgeschlossen werden kann - es funzt ja jetzt.

**Comment by phoebusryan** [comment]
Ich habe einfach alle Möglichkeiten standardmässig drin. Der eine oder andere möchte es ja nutzen. Ich persönlich nutze es aber nicht. Und da es nun funktioniert: Closed.
