### ISSUE TITLE
Links und Bilder

### ISSUE THREAD

**Issue by olien** [phoebusryan/rex_markitup#19]
Hi,

ich habe die Version 1.3.0 via Installer installiert. Eine ältere Version war nicht installiert.
Dann habe ich ein Modul (Textile) mit dem Beispielcode erstellt.

Angaben zu Links und Bilder werden nicht geparst sondern im Frontend so ausgegeben wie im Backend erstellt. (Ausprobiert in zwei unterschiedlichen REX5 Installationen).

**"System":/system.html**

**!index.php?rex_media_type=markitupImage&rex_media_file=test.jpg()!**

LG
Oliver

**Comment by phoebusryan** [comment]
Also ist es ein Problem des Outputparsers?

**Comment by olien** [comment]
ich denke schon

**Comment by tbaddade** [comment]
> Also ist es ein Problem des Outputparsers?

Jein. Du musst Textile "redaxo" als url_scheme übergeben. Siehe https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/textile/lib/textile.php#L217-L225

**Comment by phoebusryan** [comment]
Ah, also muss man den Parser erweitern. Danke fürs Feedback Thomas. Ich werds asap fixen.

**Comment by phoebusryan** [comment]
Fix ist drin in Version 1.3.1. Eine Neuinstallation ist nicht notwendig.
