### ISSUE TITLE
Textfeld passt sich nicht an

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_markitup#21]
1. Text in das Textfeld kopieren 
1. Wort markieren
1. als Headline auszeichnen

letzter Teil des Text verschwunden.

Textfeld kann man nicht manuell anpassen. (rechte untere Ecke anfassen und ziehen)

**Comment by phoebusryan** [comment]
...glaube das klappt bei mir. Evtl. mache ich es aber auch einfach anders. Kannst du mir das noch genauer erklären? Evtl. mit einem Beispiel oder einem Screenshot?

**Comment by tbaddade** [comment]
Ich kopiere einiges an Textzeilen aus einem PDF in das textarea und markiere dann paar Wörter als Headline. Dadurch das das heading 2 Leerzeilen oberhalb un eine unterhalb bekommt rutscht der Text immer weiter nach unten. Der letzte Teil des Textes ist dann irgendwann nicht mehr zu sehen.

**Comment by phoebusryan** [comment]
Das ist (vermutlich) gefixt nun. Version geht gleich mit anderen Fixes online.
