### ISSUE TITLE
Buttons fixed setzen oder max. Textfeldhöhe

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_markitup#22]
Bei sehr langen Text muss man ziemlich oft scrollen um Text auszuzeichnen. Mir fällt dazu nur ein, dass man ggf. die Textarea in der Höhe begrenzt oder links vom Textfeld die Toolbar fixed setzt.

**Comment by phoebusryan** [comment]
Wird definitiv in Kürze kommen

Notiz für mich: http://www.jacklmoore.com/autosize/#faq-min-max

**Comment by phoebusryan** [comment]
Umgesetzt in Version 2.0 (Kommt nächste Woche raus)
