### ISSUE TITLE
Leerer Title-Tag bei einem Bild verhindert Rendern des korrekten Bildlinks

### ISSUE THREAD

**Issue by polarpixel** [phoebusryan/rex_markitup#25]
Wenn ein Bild über das Medienpool-Icon eingefügt wird und kein Ttile-Tag hinterelgt ist, erzeugt das einen Link wie:
!index.php?rex_media_type=markitupImage&rex_media_file=imag1016.jpg()!
Diese Zeile wird dann aber nicht via Textile gerendert.

Vorschlag: keine runden Klammer setzen, wenn das Title-Tag-Feld leer ist.

**Comment by phoebusryan** [comment]
Fix ist im Forum und wird geprüft:
http://www.redaxo.org/de/forum/module-aktionen-f44/akkordeon-tabs-t21071.html#p118341
