### ISSUE TITLE
Fehler nachdem ein Slice mehrfach eingebunden wurde (REX 5.1)

### ISSUE THREAD

**Issue by olien** [phoebusryan/rex_markitup#26]
`/redaxo/src/addons/rex_markitup/vendor/php-textile/src/Netcarver/Textile/Parser.php on line 346
Fatal error: Cannot redeclare class Netcarver\Textile\Parser
`

LG
Oliver

**Comment by phoebusryan** [comment]
Was meinst du mit "mehrfach eingebunden"? Wenn du mehrere Slices mit dem gleichen Modul einsetzt, und dieses Modul auf markitup setzt? Dann wäre es easy zu fixen

**Comment by olien** [comment]
Wenn ich das Modul einfach in einem Artikel mehrfach benutze...

**Comment by phoebusryan** [comment]
Ja, dann sollte es der Skypefix eigentlich tun - sag bescheid.

**Comment by phoebusryan** [comment]
Klappt das?

**Comment by olien** [comment]
Sorry. Kam noch nicht dazu. Teste heute Abend!!!!

**Comment by olien** [comment]
Funktioniert
