### ISSUE TITLE
Sprache bei Tabelle einfügen

### ISSUE THREAD

**Issue by polarpixel** [phoebusryan/rex_markitup#3]
Die Popups zum Definieren von Spalten und Zeilen sind auf englisch: "How many rows", "how many cols".

Sollte möglichst in deutsch sein und übersetzbar via lang-Datei.

**Comment by phoebusryan** [comment]
Es ist nun erstmal Deutsch. Ich schau mal, wie ich das rausführen kann. Redaxo stellt ja aktuell keine Möglichkeit für JS-basierte Langfiles bereit.

**Comment by polarpixel** [comment]
Stimmt. Wäre aber vielleicht ein Feature-Wunsch für Redaxo ... ?

**Comment by phoebusryan** [comment]
Ja auf jeden Fall. Wäre was für das Addon wildcard (oder heisst es nun sprog?). Sprachvariablen in JS hätte ich auf jeden Fall schon häufig benötigt in R4.
