### ISSUE TITLE
Feedback von Peter

### ISSUE THREAD

**Issue by phoebusryan** [phoebusryan/rex_markitup#30]
Evtl. nicht die neuste Textile-Parser Library drin

**Comment by polarpixel** [comment]
Hier also das Problem, das mir kürzlich auffiel, als ich nicht das Textile-AddOn, sondern Dein enthaltenes verwendete: Interne Links werden nicht korrekt geparst:

Beispiel:
"Service":redaxo://3

Heraus kommt dann:
“Service”:./index.php?article_id=3&clang=1

Externe Links klappen.

**Comment by phoebusryan** [comment]
Was ist falsch an dem internen Link?

**Comment by polarpixel** [comment]
Genau!

**Comment by tbaddade** [comment]
Zu beachten wären auch die Sprachen. Bsp: `"Service":redaxo://3-2`

**Comment by polarpixel** [comment]
Ja. Wobei der Fall nur extrem selten vorkommen wird, dass man von einer Sprache in die andere verlinkt. Sprich: Als Default sollte eine Zahl reichen und der Link auf den Artikel der gleichen Sprache führen.
Beim Redactor ist es vermutlich ähnlich?

**Comment by phoebusryan** [comment]
Ja, das Problem wäre dasselbe. Die Linkmap lässt aber Links in die andere Sprache gar nicht zu.. oder irre ich mich da?

**Comment by polarpixel** [comment]
Ja, Du hast meines Wissens recht.
Aus meiner Sicht wäre es auch völlig ausreichend, bei via Linkmap gesetzten Links nur die aktuelle Sprache zu berücksichtigen. War bisher auch immer so.
